crudapplication/urls.py
from django.contrib import admin
from django.urls import path
# from crudapplication import views
from crudapplication.views import salary, views

urlpatterns = [
    path('create', views.create, name='create'),
    path('show', views.show, name='show'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('update/<int:id>', views.update, name='update'),
    path('addsalary', salary.addsalary, name='addsalary'),

]

webapplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crudapplication/', include('crudapplication.urls')),
]

crudapplication/models/models.py
from django.db import models


class Employee(models.Model):
    empid = models.CharField(max_length=10)
    empname = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    contact = models.CharField(max_length=15)

    class Meta:
        db_table = 'employees'

crudapplication/models/salary.py
from django.db import models
from .models import Employee


class Salary(models.Model):
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)

    class Meta:
        db_table = 'salary'

crudapplication/forms.py
from django import forms
from crudapplication.models import Employee, Salary


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"


class SalaryForm(forms.ModelForm):
    class Meta:
        model = Salary
        fields = "__all__"

crudapplication/views/salary.py
from django.shortcuts import render, redirect
from crudapplication.forms import SalaryForm
from crudapplication.models.models import Employee
from crudapplication.models.salary import Salary


def addsalary(request):
    employees = Employee.objects.all()
    if request.method == 'POST':
        form = SalaryForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            pass
    else:
        form = SalaryForm()
    context = {'form': form, 'employees': employees}
    return render(request, 'add_salary.html', context)

crudapplication/views/views.py
from django.shortcuts import render, redirect
from crudapplication.forms import EmployeeForm, SalaryForm
from crudapplication.models.models import Employee


def create(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect(show)
            except:
                pass
    else:
        form = EmployeeForm()
    context = {'form': form}
    return render(request, 'create.html', context)


def show(request):
    employees = Employee.objects.all()
    context = {'employees': employees}
    return render(request, 'show.html', context)


def delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect(show)


def edit(request, id):
    employee = Employee.objects.get(id=id)
    context = {'employee': employee}
    return render(request, 'edit.html', context)


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect(show)
    else:
        pass

crudapplication/templates/add_salary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
    <table border="1" align="center" cellpadding="10" cellspacing="0">
          <tr>
            <td>Employees</td>
            <td>
                <select id="id_employee" name="employee">
                    <option value="">Select Employee</option>
                   {% for emp in employees %}
                    <option value="{{ emp.id }}">{{ emp.empname }}</option>

                   {% endfor %}

                </select>

            </td>
        </tr>
        <tr>
            <td>Salary</td>
            <td><input type="text" id="id_salary" name="salary">

            </td>
        </tr>


         <tr>
            <td colspan="2" align="center">
                <input type="submit" id="submit" name="submit" value="Submit">
            </td>
        </tr>
    </table>
    </form>
</body>
</html>

crudapplication/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
    <table border="1" align="center" cellpadding="10" cellspacing="0">
          <tr>
            <td>Employee Id</td>
            <td><input type="text" id="id_empid" name="empid">

            </td>
        </tr>
        <tr>
            <td>Employee Name</td>
            <td><input type="text" id="id_empname" name="empname">

            </td>
        </tr>
         <tr>
            <td>Email</td>
            <td><input type="text" id="id_email" name="email"> </td>
        </tr>
         <tr>
            <td>Contact</td>
            <td><input type="text" id="id_contact" name="contact"> </td>
        </tr>
         <tr>
            <td colspan="2" align="center">
                <input type="submit" id="submit" name="submit" value="Submit">
            </td>
        </tr>
    </table>
    </form>
</body>
</html>

crudapplication/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Student</title>
</head>
<body>


    <form method="post" action="/crudapplication/update/{{ employee.id }}">
        {% csrf_token %}
    <table border="1" align="center" cellpadding="10" cellspacing="0">
          <tr>
            <td>Employee Id</td>
            <td><input type="text" id="id_empid" name="empid" value="{{ employee.empid }}">

            </td>
        </tr>
        <tr>
            <td>Employee Name</td>
            <td><input type="text" id="id_empname" name="empname" value="{{ employee.empname }}">

            </td>
        </tr>
         <tr>
            <td>Email</td>
            <td><input type="text" id="id_email" name="email" value="{{ employee.email }}"> </td>
        </tr>
         <tr>
            <td>Contact</td>
            <td><input type="text" id="id_contact" name="contact" value="{{ employee.contact }}"> </td>
        </tr>
         <tr>
            <td colspan="2" align="center">
                <input type="submit" id="submit" name="submit" value="Update">
            </td>
        </tr>
    </table>
    </form>
</body>
</html>

crudapplication/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Display All Users</title>
</head>
<body>
    <a href="create">Add New Employee</a>
    <table border="1" align="center" cellspacing="0" cellpadding="10">
        <tr bgcolor="silver">
            <td>EmployeeID</td>
            <td>EmployeeName</td>
            <td>Email</td>
            <td>Contact</td>
            <td>Actions</td>
        </tr>
        {% for emp in employees %}
            <tr>
                <td>{{ emp.empid }}</td>
                <td>{{ emp.empname }}</td>
                <td>{{ emp.email }}</td>
                <td>{{ emp.contact }}</td>
                <td>
                    <a href="edit/{{ emp.id }}">Edit</a>
                    <a href="delete/{{ emp.id }}">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>